### ISSUE TITLE
Java installed, but YUI and GCC don't work...

### ISSUE THREAD

**Issue by Ronald-Diemicke** [armin-pfaeffle/atom-minify#12]
I'm running Windows 7 and I'm getting an error that Java isn't installed when I run the JS minification using either YUI or GCC; but I do have java installed. Is there a specific version of Java needed? Where is it looking to determine if java is installed?

**Comment by armin-pfaeffle** [comment]
What happens if you open the terminal and enter `java -version`? Can you send me the output?

If there occurs a message that command cannot be found, then a path to your Java installation is missing in your `PATH` variable.

**Comment by Ronald-Diemicke** [comment]
Here's the output of java -version:
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

We're using an older version for development purposes, but I know the path to my java installation is in my path variable.

**Comment by armin-pfaeffle** [comment]
That's interessting... My Java check code:

```
    checkJavaInstalled: (callback) ->
        exec = require('child_process').exec
        command = 'java -version'
        result = exec(command, {}, (err, stdout, stderr) ->
            isInstalled = err is null
            version = undefined
            if isInstalled
                matches = stderr.match(/"(.+?)"/)
                if matches
                    version = matches[1]
            callback(isInstalled, version)
        )
```

This method calls `java -version` and looks at the result. The code extracts the version, but this information is not used.

Do you want to help me to find out what's going wrong here? Can you modifiy the file `C:\Users\<username>\.atom\packages\atom-minify\lib\minifier\BaseMinifier.coffee` and add some console-commands before line 6, so it looks like the followin:

```
        result = exec(command, {}, (err, stdout, stderr) ->
            console.log err
            console.log stdout
            console.log stderr
            isInstalled = err is null
```

After that, reload your Atom application via CTRL+ALT+R. After that, open the console in Atom via CTRL+ALT+I and select console tab. Then try to modify a file and have a look at the output. Please post it here!

**Comment by Ronald-Diemicke** [comment]
Here's the result:

BaseMinifier.coffee:6 Error: Command failed: C:\windows\system32\cmd.exe /s /c "java -version"
Error: could not open `C:\Program Files (x86)\Java\jre1.7.0_75\lib\i386\jvm.cfg'
 {killed: false, code: 1, signal: null, cmd: "C:\windows\system32\cmd.exe /s /c "java -version"", stack: (...)…}

BaseMinifier.coffee:7 

BaseMinifier.coffee:8 Error: could not open `C:\Program Files (x86)\Java\jre1.7.0_75\lib\i386\jvm.cfg'

I'm curious why its going after my java 1.7 install rather than using the JAVA_HOME variable for the path?

**Comment by armin-pfaeffle** [comment]
Well... I think something is "wrong" with your Java installation or with your `PATH` variable? Can you post it? And don't forget, there are two: your private of your profile and the system PATH variable :)

**Comment by Ronald-Diemicke** [comment]
This is my System level PATH variable:
C:\Program Files (x86)\iis express\PHP\v5.4;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Encentuate\AccessAgent\Integration\Carefx\Fusionfx;C:\Program Files\Encentuate\;C:\Program Files (x86)\Lotus\Notes\;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\WinMerge;C:\Java\jdk1.6.0_45\bin;C:\apache-maven-3.0.5\bin;C:\adobe\vault-cli-2.3.6\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\nodejs\;C:\Users\nz5wb8\AppData\Local\atom\bin;C:\Users\nz5wb8\AppData\Roaming\npm;C:\apache-ant-1.9.6\bin;C:\Program Files\1E\NomadBranch\;C:\cygwin64\bin

This is the user PATH variable:
C:\Users\nz5wb8\AppData\Local\atom\bin;C:\Users\nz5wb8\AppData\Roaming\npm

Also - I have a system level variable that's JAVA_HOME that has a value of:
C:\Java\jdk1.6.0_45

**Comment by Ronald-Diemicke** [comment]
So I've moved a copy of the version of JAVA it was looking for into the directory it was looking for it in and there's now another error:
![image](https://cloud.githubusercontent.com/assets/5161807/9548547/bd8454c4-4d66-11e5-875e-8a808bb32983.png)

**Comment by armin-pfaeffle** [comment]
I don't see any any reason why your terminal uses 1.6 installation and Atom tries to use 1.7...

What is the output when you enter `where java` into terminal?

**Comment by Ronald-Diemicke** [comment]
The output from 'where java' is:
C:\Java\jdk1.6.0_45\bin\java.exe

I wish I were on my MBP... I feel like this is about par for the course for windows.

**Comment by armin-pfaeffle** [comment]
Well, it's only a guess, but I think the context under which Atom or the command execution is running, is different from your normal terminal. I don't see other reasons for that...

The only thing I can offer you, is to have a look on your system. Via TeamViewer? If you want me to help you, please contact me via mail@armin-pfaeffle.de

**Comment by Ronald-Diemicke** [comment]
I appreciate that, but unfortunately this is a corporate machine... and I'm pretty sure the IT security folks wouldn't appreciate that. I might try hacking away at the code to see if I force it to work with my java version or maybe even have something to hard set the java path I want it to use.

**Comment by armin-pfaeffle** [comment]
You can try the following modifications:

``` js
// file: minifier/BaseMinifier.coffee:2
checkJavaInstalled: (callback) ->
    callback(true)
```

Modify the following three files
- minifier/css/yui-css.coffee
- minifier/js/gcc.coffee
- minifier/js/yui-css.coffee

Search for the lines that begin with `command = 'java` and add the absolute path to your Java installation:

``` js
command = '"C:\\Java\\jdk1.6.0_45\\bin\java.exe" ...'
```

Ensure that you add two backslashes and perhaps you need the quotes!

**Comment by armin-pfaeffle** [comment]
Btw: What about not using the Java-requiring-minifiers?

**Comment by Ronald-Diemicke** [comment]
That's an option - but I was trying to get YUI or GCC to work because UglifyJS2's output seemed to be causing me some issues - so I wanted to see if it was consistent across all minification apps.

**Comment by armin-pfaeffle** [comment]
I can give you that answer: Nope! Most times, the output is different! ;)

**Comment by Ronald-Diemicke** [comment]
Well that's a good thing because maybe I won't encounter the same issues with GCC and YUI if I can get either to work :)

**Comment by armin-pfaeffle** [comment]
Try it with the absolute path, but with each update, you have to modify that.

**Comment by armin-pfaeffle** [comment]
Have you tried the fix?

Can I close this issue?!

**Comment by Ronald-Diemicke** [comment]
Yup. Sorry. The fix seems to work. It'd be nice if we could override the java path in the UI in the settings/options area for this module - but this is good for now :)

**Comment by armin-pfaeffle** [comment]
Please check latest version 0.4. There I added an advanced option at the end of the options. There you can define an absolute path to your Java executable.

Please tell me if it works for you!

**Comment by yagrand3z** [comment]
> Please check latest version 0.4. There I added an advanced option at the end of the options. There you can define an absolute path to your Java executable.
> 
> Please tell me if it works for you!

Thanks you. Its working
