### ISSUE TITLE
set gcc compilation_level and other options per file

### ISSUE THREAD

**Issue by tobsn** [armin-pfaeffle/atom-minify#13]
// minifier: gcc, options: --compilation_level WHITESPACE_ONLY

this would be great!
also support of per file js_externs etc.

right now I do this per file and handle it via copy and paste (doesn't happen so often with gcc):
// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level ADVANCED_OPTIMIZATIONS
// @js_externs window['LP'].geo
// ==/ClosureCompiler==

to preserve namspacing etc. - would be awesome if this could get passed along from the file to the binary as options.

**Comment by armin-pfaeffle** [comment]
Hey!

Yes, you are right! My package does not support options at the moment. I will change that during the next weeks. I must find some free time before ;) but it's on my agenda!

**Comment by tobsn** [comment]
awesome :)

**Comment by armin-pfaeffle** [comment]
Sorry that I'm so late with that feature, but I published verion 0.6.0 right now which provides minifier options. Please [read this](https://github.com/armin-pfaeffle/atom-minify/blob/master/OPTIONS.md) for more information about that and let me know if it fits your needs!
