### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' ...

### ISSUE THREAD

**Issue by ghost** [armin-pfaeffle/atom-minify#17]
Hello, I just installed this package and set it up with uglifyJS2. Whenever I try to minify some javascript (even an empty document) I get a panel with the error:

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self".

Am I doing something wrong? Any suggestions appreciated :)

**Comment by armin-pfaeffle** [comment]
Hey! Well, I never had this problem.

Can you check which version of UglifyJs and node.js you have installed? Which system do you use? Windows? Linux? Mac OS?

**Comment by ghost** [comment]
I'm on osx 10.11. I just downloaded the atom 1.2 binary and installed
atom-minify via the package interface. How do I check which version of
uglifyjs / node.js I'm using? I also installed the atom-uglify package you
reference and that actually works perfectly. Do you think that's because
atom-uglify is now incorporating the eval loophole? Cheers!

**Comment by armin-pfaeffle** [comment]
I don't need that information any more, because I updated everything and I got the same error. I will have a closer look ath this.

**Comment by armin-pfaeffle** [comment]
I fixed this bug with latest version 0.6.1

**Comment by ghost** [comment]
Works perfect; thank you for awesome package! :)

**Comment by armin-pfaeffle** [comment]
Thanks! Nice to hear ;)
