### ISSUE TITLE
necessary whitespace on css calc() function

### ISSUE THREAD

**Issue by turkhero** [armin-pfaeffle/atom-minify#22]
atom-minify extensions removes a necessary whitespace after and before plus sign in css calc() function.

**Comment by armin-pfaeffle** [comment]
Hey!

My packages does not minify anything ;) It only uses one of four CSS compressors. Have you tried to use another one? This is a bug of the corresponding compressor.

**Comment by turkhero** [comment]
oh ok, thank you

**Comment by armin-pfaeffle** [comment]
Can you tell me, which compressor you used and do you have a simple example? This could be interessting for others!

**Comment by turkhero** [comment]
YUI-Compressor is bugged. clean-css and Sqwish are working fine.

**Comment by armin-pfaeffle** [comment]
Thanks!
