### ISSUE TITLE
UglifyJS2 source map generation not working?

### ISSUE THREAD

**Issue by sudofx** [armin-pfaeffle/atom-minify#24]
Am I doing something wrong?
source_map = $1.min.$2.map

Everytime I save my js file, I get this error in the Atom console: "WARN: Couldn't figure out mapping for " and the source map is never generated.

Please help. :-)

**Comment by armin-pfaeffle** [comment]
Hey! I published a new version which fixes that bug. Now you can use this feature as expected!
