### ISSUE TITLE
Handle "spawn cmd.exe ENOENT"

### ISSUE THREAD

**Issue by Neui** [armin-pfaeffle/atom-minify#26]
I specified a custom Java-executable path, however, this package still complains about java not being installed. So i looked at the code and did some logging. The contents of `err` is `spawn cmd.exe ENOENT`. After quick googeling says, that you may need to include `C:/Windows/System32` for the path-variable. For testing, i added `{env: {path: "C:/Windows/System32"}}` to the 2<sup>nd</sup> parameter of `exec` in `BaseMinifier.coffe` and `js/gcc.coffee` and it worked.

So either:
- Do the "workaround" i did (requires code for adding the path-variable)
- Say that they might need to add `C:/Windows/System32` to the `PATH`-Variable (actually untested).

**Comment by armin-pfaeffle** [comment]
Hey!

Perhaps I can add a check for Windows installations if there is no `C:/Windows/System32` path in PATH variable., so my package adds it automatically.

But I think it's a general problem if this path is missing. On every Windows installation I checked, `C:/Windows/System32` is existant. Why there are installations where it's missing? This problems goes further: cmd cannot access applications placed in the system path, e.g. PING.EXE or IPCONFIG.EXE. So again: why is this path missing on some installations?

Perhaps you can help me answering this question?

**Comment by Neui** [comment]
I actually tested more and came to the conclusion, that this is not your mistake. Sorry. This can be closed. The package causing this is [python-tools](https://github.com/MichaelAquilina/python-tools/). There is a PR, which fixes that.

If you are curious and want more information:

`process.env.Path` is the "real" path-variable on my machine. Now, some other package tries to be clever and wants to add some paths into that variable.. But it uses `process.env.PATH` (uppercase), which doesn't exists at that point, the package fills in some paths. The "shell" seems to use the `PATH` over `Path`, thus it won't find anything (but python).

Oh and by the way, there is `C:\Windows\system32` in `process.env.Path`, so it works with that package disabled.

**Comment by armin-pfaeffle** [comment]
Yes, you are totally right! Here some more explanation about that: in my [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) packages I modify the `process.env.PATH` variable too, but only a _copy_ and not the original one.

``` coffeescript
environment = Object.create(process.env) # Creates a copy
if typeof searchPath is 'string' and searchPath.length > 1
    environment.PATH += ":#{searchPath}"

exec command, { env: environment }, (error, stdout, stderr) =>
    # ...
```
