### ISSUE TITLE
Seperate text properly in Notifications

### ISSUE THREAD

**Issue by Neui** [armin-pfaeffle/atom-minify#27]
If the notification-type is set to "Notification" and "Show saving info" is checked and a notification is sent, the text for the saving-info is not seperated properly.
![Notification](https://cloud.githubusercontent.com/assets/1196130/16152702/692ea508-34a3-11e6-895b-19ea8e33c568.png)

**Comment by armin-pfaeffle** [comment]
Thanks! Is fixed with 0.7.5!
