### ISSUE TITLE
Error: Command failed: java - server -XX:+TieredCompilation -jar -Xss2048k

### ISSUE THREAD

**Issue by AntMayes** [armin-pfaeffle/atom-minify#34]
Having an error with Atom Minify and my javascript file.

It seems that it is pointing towardsthe atom-minify packages and the gcc-20151015.jar file.

Can someone please explain anything further on correcting this?

Thanks,

**Comment by armin-pfaeffle** [comment]
Hey!

Is Java installed in your machine?

**Comment by AntMayes** [comment]
My apologies for the delay.

It was a misdirection to the wrong folder.

It seems to be working now

Thank you

**Comment by armin-pfaeffle** [comment]
Great!
