### ISSUE TITLE
Allow to close progress/success panel with escape key

### ISSUE THREAD

**Issue by EzraLopez** [armin-pfaeffle/atom-minify#36]
Just like the find and replace feature allows to close its panel with the escape key, is it possible to for atom-minify to do it as well?

**Comment by armin-pfaeffle** [comment]
I think I can add that, yes ;) See version 0.8.0, I published seconds ago.

**Comment by EzraLopez** [comment]
Perfect! Thanks! :)

**Comment by EzraLopez** [comment]
Works great!
