### ISSUE TITLE
Error when trying to minify

### ISSUE THREAD

**Issue by rdebeasi** [armin-pfaeffle/atom-minify#4]
When I try to minify a file, I get the following error. Do I need to install Java in order to use this plugin? Thanks! :)

Command failed: C:\Windows\system32\cmd.exe /s /c "java -server -XX:+TieredCompilation -jar -Xss2048k "C:\Users\rdebe_000.atom\packages\atom-minify\node_modules\node-minify\lib/google_closure_compiler-v20130411.jar" --js="C:\Users\rdebe_000\Documents\Projects\flexMenu\flexmenu.js" --language_in=ECMASCRIPT3 --js_output_file="C:\Users\rdebe_000\Documents\Projects\flexMenu\flexmenu.min.js" "
'java' is not recognized as an internal or external command,
operable program or batch file.

**Comment by armin-pfaeffle** [comment]
Hey! Yes, you need to install Java for YUI (CSS and JS compressor) and Google Closure Compiler.

I will update the documentation soon, but before I rewrite the complete package. About 80% is finished.

**Comment by armin-pfaeffle** [comment]
With version 0.2 I included a Java-check when using YUI oder GCC. If Java is not present, you see an error message.

PS: You can use UglifyJS2 as Javascript minifier, so you don't need to install Java.

**Comment by odahcam** [comment]
What is the right Java (JRE/JDK/...) to install?

**Comment by armin-pfaeffle** [comment]
JRE should do it.  I've installed Java 8 Update 121.
