### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by markpanado** [armin-pfaeffle/atom-minify#44]
Argument to `path.dirname` must be a string
```
Object.dirname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
InlineParameterParser.parseFirstLineParameter (/Users/markpanado/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:72:46)
InlineParameterParser.parse (/Users/markpanado/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:17:21)
AtomMinifier.minify (/Users/markpanado/.atom/packages/atom-minify/lib/minifier.coffee:57:30)
Object.minify (/Users/markpanado/.atom/packages/atom-minify/lib/atom-minify.coffee:408:28)
<unknown> (/Users/markpanado/.atom/packages/atom-minify/lib/atom-minify.coffee:264:28)
```

**Comment by armin-pfaeffle** [comment]
I cannot confirm that? Which version of atom-minify do you use? Can you post the steps to reproduce that? Which minifier do you use?

**Comment by markpanado** [comment]
Sorry I think this was poster automatically by Atom after I got the error. I don't experience this error again . Closing this now. Thank you.

**Comment by biblioman** [comment]
There seems to be some conflict between atom-minify and less-autocompile 1.0.0: a message on a deprecation error on atom-minify shows up when less-autocompile starts working.

Argument to path.dirname must be a string

Object.dirname - C:\Users\AN\AppData\Local\atom\app-1.17.0\resources\app\src\electron-shims.js:9:10
InlineParameterParser.parseFirstLineParameter - C:\Users\AN\.atom\packages\atom-minify\lib\helper\inline-parameter-parser.coffee:72:46
InlineParameterParser.parse - C:\Users\AN\.atom\packages\atom-minify\lib\helper\inline-parameter-parser.coffee:17:21
AtomMinifier.minify - C:\Users\AN\.atom\packages\atom-minify\lib\minifier.coffee:57:30
Object.minify - C:\Users\AN\.atom\packages\atom-minify\lib\atom-minify.coffee:408:28
<unknown> - C:\Users\AN\.atom\packages\atom-minify\lib\atom-minify.coffee:264:28

**Comment by ickas** [comment]
Same problem here, any solution?

- `Argument to path.dirname must be a string`
- `Object.dirname - /Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:9:10`
- `InlineParameterParser.parseFirstLineParameter - /Users/henrique/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:72:46`
- `InlineParameterParser.parse - /Users/henrique/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:17:21`
- `AtomMinifier.minify - /Users/henrique/.atom/packages/atom-minify/lib/minifier.coffee:57:30`
- `Object.minify - /Users/henrique/.atom/packages/atom-minify/lib/atom-minify.coffee:408:28`
-  `<unknown> - /Users/henrique/.atom/packages/atom-minify/lib/atom-minify.coffee:264:28`

**Comment by vlastapolach** [comment]
Hi, I have got same error in Atom: 
Atom v. 1.19.1
Atom-minify v. 0.8.0

```
Argument to path.dirname must be a string
Report Issue
Object.dirname - /Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:9:10
InlineParameterParser.parseFirstLineParameter - /Users/vp/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:72:46
InlineParameterParser.parse - /Users/vp/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:17:21
AtomMinifier.minify - /Users/vp/.atom/packages/atom-minify/lib/minifier.coffee:57:30
Object.minify - /Users/vp/.atom/packages/atom-minify/lib/atom-minify.coffee:408:28
<unknown> - /Users/vp/.atom/packages/atom-minify/lib/atom-minify.coffee:264:28
```
Any way to kill the error message? :) 
Thank you

**Comment by vlastapolach** [comment]
Hi, I have got same error in Atom: 
Atom v. 1.19.1
Atom-minify v. 0.8.0

```
Argument to path.dirname must be a string
Report Issue
Object.dirname - /Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:9:10
InlineParameterParser.parseFirstLineParameter - /Users/vp/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:72:46
InlineParameterParser.parse - /Users/vp/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:17:21
AtomMinifier.minify - /Users/vp/.atom/packages/atom-minify/lib/minifier.coffee:57:30
Object.minify - /Users/vp/.atom/packages/atom-minify/lib/atom-minify.coffee:408:28
<unknown> - /Users/vp/.atom/packages/atom-minify/lib/atom-minify.coffee:264:28
```
Any way to kill the error message? :) 
Thank you

**Comment by markpanado** [comment]
Sorry guys I don't use Atom anymore. I already moved to VS Code.

**Comment by jonhyleo** [comment]
Hi, I have got same error in Atom:
OS: Win7 x64
Atom v. 1.19.5
Atom-minify v.0.8.0


Object.dirname - C:\Users\Administrador\AppData\Local\atom\app-1.19.2\resources\app\src\electron-shims.js:9:10
InlineParameterParser.parseFirstLineParameter - C:\Users\Administrador\.atom\packages\atom-minify\lib\helper\inline-parameter-parser.coffee:72:46
InlineParameterParser.parse - C:\Users\Administrador\.atom\packages\atom-minify\lib\helper\inline-parameter-parser.coffee:17:21
AtomMinifier.minify - C:\Users\Administrador\.atom\packages\atom-minify\lib\minifier.coffee:57:30
Object.minify - C:\Users\Administrador\.atom\packages\atom-minify\lib\atom-minify.coffee:408:28
<unknown> - C:\Users\Administrador\.atom\packages\atom-minify\lib\atom-minify.coffee:264:28

**Comment by oraimbaud** [comment]
Hi!
Also same error, it appears when I save scss files with sass-autocompile v. 0.13.5
macOS Sierra v. 10.12.6
Atom v. 1.23.3
atom-minify v. 0.8.0

`Argument to path.dirname must be a string`

`Object.dirname - /Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:9:10
InlineParameterParser.parseFirstLineParameter - /Users/benediktfrommer/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:72:46
InlineParameterParser.parse - /Users/benediktfrommer/.atom/packages/atom-minify/lib/helper/inline-parameter-parser.coffee:17:21
AtomMinifier.minify - /Users/benediktfrommer/.atom/packages/atom-minify/lib/minifier.coffee:57:30
Object.minify - /Users/benediktfrommer/.atom/packages/atom-minify/lib/atom-minify.coffee:408:28
<unknown> - /Users/benediktfrommer/.atom/packages/atom-minify/lib/atom-minify.coffee:264:28`
