### ISSUE TITLE
Support for ECMA2016 =>

### ISSUE THREAD

**Issue by jeffersonmello** [armin-pfaeffle/atom-minify#45]
I tried minify the follow code 

`this.$http.get('url',
      {
        params: {
          imeinumber: imei,
          metodo: 'getuser',
          crpt: 'C3DF32EA11'
        }

      }).then(response => {

        this.varusuario  = response.body;
      },  response => {
        console.log(response);
      });`

and returned error, in https://jscompress.com/ with ECMAScript 2016 checked minify with success

**Comment by jeffersonmello** [comment]
solved changed for google closure compiler

**Comment by armin-pfaeffle** [comment]
Sorry for my later answer. My package does not compile anything, it's only a wrapper for YUI Compressor, Google Closure Compiler, UglifyJS2. So you have to check if one if these compilers support ES6+.

Please let me know if you need further support.

**Comment by markpanado** [comment]
@armin-pfaeffle how can we use the **UglifyJS2 Harmony** branch? I don't want to use **GCC** because it's too slow... **UglifyJS2 Harmony** branch uses ES6.

**Comment by armin-pfaeffle** [comment]
Hm... That's a good idea! I will check this next few days!
