### ISSUE TITLE
Cannot minify when adding class to DOM object in JS/Jquery

### ISSUE THREAD

**Issue by SimpenSimon** [armin-pfaeffle/atom-minify#47]
This is the part of the code that doesn't work (with a different id, src and class name) :

    newObject = $('<img />', {
        id: 'image',
        src: 'image.jpg',
        class: 'greatClassName'
    });

if I either remove "class" or change it to "className" the file will be minified but it will not add the class to the object. However, if I save the file without minifying it and using the code above, then the object will get the class so I know that it's a bug in the minifyer and not with the code itself.

**Comment by armin-pfaeffle** [comment]
Have you tried another minifier? Which one do you use?

The minifiers itself are not my projects. atom-minify is only a wrapper and does not minify anything.
