### ISSUE TITLE
Support ES6 arrow?

### ISSUE THREAD

**Issue by pu3antasyah** [armin-pfaeffle/atom-minify#57]
Uglify not support ES6 arrow? Here is code and error messages is `SyntaxError: Unexpected token: oprator (>)`.

```
function return_after_2_second(x) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(x * 2)
   }, 300)
  })
}
```

**Comment by armin-pfaeffle** [comment]
I must add UglifyJS3, because only there ES6 is supported.
