### ISSUE TITLE
atom.io discussion thread

### ISSUE THREAD

**Issue by BMOv2600** [armin-pfaeffle/atom-minify#6]
Not really an issue w/minify so much as noting that the atom link on the repo front page ("have a look at the discussion thread on atom.io") doesn't appear to be working. 

Is there a discussion thread on Atom somewhere?

**Comment by armin-pfaeffle** [comment]
Thanks! There was no thread until today. With version 0.2.2 I created a discussion thread and fixed the link in the documentation.
