### ISSUE TITLE
Java Detection Problem

### ISSUE THREAD

**Issue by acceptableEngineering** [armin-pfaeffle/atom-minify#9]
With a JS file open, I select Packages -> Minify -> Minify to minified file and received the following popup:
<img width="532" alt="screen shot 2015-08-11 at 4 27 50 pm" src="https://cloud.githubusercontent.com/assets/5241549/9213326/0597fa82-4046-11e5-9fb2-b576b5640ac0.png">

The issue is that I do indeed have the latest version of Java (JRE) installed:
<img width="457" alt="screen shot 2015-08-11 at 4 27 57 pm" src="https://cloud.githubusercontent.com/assets/5241549/9213325/05940a8a-4046-11e5-9039-be757362beaf.png">

Strangely enough I use a Package with Sublime Text 2 which started having the same error a while back (on a different machine running a different version of Mac OS.)

**Comment by armin-pfaeffle** [comment]
What was the problem? How have you fixed it?

**Comment by lhoumeau** [comment]
Same issue for me after High Sierra upgrade : "You need to install Java in order to user YUI compressor or set a correct path to Java executable in options" AND latest version of Java (JRE) installed.
Where can I set the correct path to Java ?
regards

**Comment by armin-pfaeffle** [comment]
Well... I don't know why, but installing JDK solved this!

**Comment by janstieler** [comment]
I have also this problem on OS X with Java Version 8 Build 211.
I have installed it but in Atom I get every time this window if I want to minify:
![](https://cloud.githubusercontent.com/assets/5241549/9213326/0597fa82-4046-11e5-9fb2-b576b5640ac0.png)

**Comment by jagirbahesh** [comment]
Hey @janstieler ,

For this issue first you need to check Java is installed or not.
If you have already installed java in your mac PC then you can see the below screen-shot:
https://prntscr.com/vw8hdd

If you have not found this icon then you need to install Java.
Go to official website for java and install java.

After installed Java you have seen java icon in settings.

For resolved this error please follow below steps after installed Java.
Go to settings -> java -> Click on java tab -> View -> User -> Path
https://prntscr.com/vw8h3s

Copy path from there and past it in Atom -> minify -> settings -> Advance->java path
Here I have shred the scrren-shot for your reference:
https://prnt.sc/vw97yj

Note: in screen-shot this is my mac pc path so, please ignore and found out your mac pc java path with above steps.

Let me know if this was helpful or if you’d like to know more! Good luck :slightly_smiling_face:
